### ISSUE TITLE
재접속할시 도로 영어로 바뀌는 문제가 있다.

### ISSUE THREAD

**Issue by 156752571** [N-Joy-Shadow/FabricChatKoreanConvertor#2]
제목 그대로 재접할시 enk를 한번 더 입력해야하는 문제가 생겼다  (As the title suggests, there is a problem that you have to input "enk" one more time.)

**Comment by myogoo** [comment]
그건의도한거임

**Comment by 156752571** [comment]
엥?

**Comment by myogoo** [comment]
플레이어들이 그 명령어를 켰는지 껐는지는 리스트에 저장되는데 플레이어가 나가면 그 플레이어를 리스트에서 삭제하도록함

**Comment by 156752571** [comment]
수정하는법 있음?

**Comment by myogoo** [comment]
MixinOnDisconnected.java  이 파일 날리면됨

**Comment by 156752571** [comment]
고맙다 ㄳㄳ 이제 이슈 닫으면되지?

**Comment by myogoo** [comment]
근데 추천은 안함

**Comment by 156752571** [comment]
나는 kakc 플러그인처럼 로갓하고 다시들어와도 한챗유지되는건줄알아서...

**Comment by myogoo** [comment]
나는 kakc를 안써봐서 모름;; 만들어 달래서 만든거임

**Comment by myogoo** [comment]
닫음
